version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker run --rm -v $PWD:$PWD -w $PWD node:7 sh -c 'npm install; npm test'
      - run:
          shell: /bin/bash
          command: |
            cp -r ./coverage/ $CIRCLE_ARTIFACTS
            bash <(curl -s https://codecov.io/bash)
            cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -v
          when: always
  build_and_push_tag:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build -t ictu/bigboat-agent-compose:latest .
            docker tag ictu/bigboat-agent-compose:latest ictu/bigboat-agent-compose:${CIRCLE_TAG}
            MAJOR_VERSION=${CIRCLE_TAG/.*}; docker tag ictu/bigboat-agent-compose:latest ictu/bigboat-agent-compose:${MAJOR_VERSION}
            MINOR_VERSION=${CIRCLE_TAG%.*}; docker tag ictu/bigboat-agent-compose:latest ictu/bigboat-agent-compose:${MINOR_VERSION}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/bigboat-agent-compose:latest
            docker push ictu/bigboat-agent-compose:${CIRCLE_TAG}
            docker push ictu/bigboat-agent-compose:${MINOR_VERSION}
            docker push ictu/bigboat-agent-compose:${MAJOR_VERSION}
  build_and_push_branch:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build -t ictu/bigboat-agent-compose:latest .
            docker tag ictu/bigboat-agent-compose:latest ictu/bigboat-agent-compose:${CIRCLE_BRANCH} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/bigboat-agent-compose:latest
            docker push ictu/bigboat-agent-compose:${CIRCLE_BRANCH}          
  build_and_push_master:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build -t ictu/bigboat-agent-compose:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/bigboat-agent-compose:latest
workflows:
  version: 2
  build_test_push:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build_and_push_master:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - build_and_push_branch:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^feature.*$/              
      - build_and_push_tag:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/